accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('', include('django.contrib.auth.urls')),

    # Switch the default landing page to be a search page
    # path('', views.dashboard, name='dashboard')
]

agent_finder/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
# from geopy.geocoders import Nominatim
from geopy.geocoders import GoogleV3
from geopy.exc import GeocoderTimedOut


class UserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifier for auth, instead of username
    """

    def create_user(self, email=None, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    class UserType(models.TextChoices):
        KIOSK_OPERATOR = 'KO', 'Kiosk Operator'
        SUPER_AGENT = 'SA', 'Super Agent'
        ALS_BET_SHOP = 'BS', 'ALSBets Shop'

    username = None
    email = models.EmailField(
        verbose_name="email address", blank=True, unique=True)
    user_type = models.CharField(
        max_length=2,
        choices=UserType.choices,
        default=UserType.KIOSK_OPERATOR
    )
    profile_completed = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email


class KioskOperatorProfile(models.Model):

    STATE_CHOICES = (
        ('AB', 'Abia'),
        ('FC', 'Abuja'),
        ('AD', 'Adamawa'),
        ('AK', 'Akwa Ibom'),
        ('AN', 'Anambra'),
        ('BA', 'Bauchi'),
        ('BY', 'Bayelsa'),
        ('BE', 'Benue'),
        ('BO', 'Borno'),
        ('CR', 'Cross River'),
        ('DE', 'Delta'),
        ('EB', 'Ebonyi'),
        ('ED', 'Edo'),
        ('EK', 'Ekiti'),
        ('EN', 'Enugu'),
        ('GO', 'Gombe'),
        ('IM', 'Imo'),
        ('JI', 'Jigawa'),
        ('KD', 'Kaduna'),
        ('KN', 'Kano'),
        ('KT', 'Katsina'),
        ('KE', 'Kebbi'),
        ('KO', 'Kogi'),
        ('KW', 'Kwara'),
        ('LA', 'Lagos'),
        ('NA', 'Nasarawa'),
        ('NI', 'Niger'),
        ('OG', 'Ogun'),
        ('ON', 'Ondo'),
        ('OS', 'Osun'),
        ('OY', 'Oyo'),
        ('PL', 'Plateau'),
        ('RI', 'Rivers'),
        ('SO', 'Sokoto'),
        ('TA', 'Taraba'),
        ('YO', 'Yobe'),
        ('ZA', 'Zamfara'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Perhaps use Postgres text search to find places based on location stored
    kiosk_location = models.CharField(max_length=255)
    # Possibly have extra details about the shop
    # Optionally have provision for images
    kiosk_id = models.CharField(max_length=50)
    # Should probably take in states too but as an enum
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    operating_hours = models.CharField(max_length=100)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    phone_number = models.CharField(max_length=15)
    is_available = models.BooleanField(default=False)

    def __str__(self):
        return f"Kiosk Operator Profile - {self.user.email}"

    def get_full_name(self):
        last_name = self.user.last_name if self.user.last_name != "N/A" else ""
        return f"{self.user.first_name} {last_name}"


class SuperAgentProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    region = models.CharField(max_length=100)
    # Should probably take in states too but as an enum
    state = models.CharField(
        max_length=2, choices=KioskOperatorProfile.STATE_CHOICES)
    # Todo: Add kiosks managed
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return f"Super Agent Profile - {self.user.email}"

    def get_full_name(self):
        last_name = self.user.last_name if self.user.last_name != "N/A" else ""
        return f"{self.user.first_name} {last_name}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == User.UserType.KIOSK_OPERATOR:
            KioskOperatorProfile.objects.create(user=instance)
        elif instance.user_type == User.UserType.SUPER_AGENT:
            SuperAgentProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, created, **kwargs):
    if instance.user_type == User.UserType.KIOSK_OPERATOR:
        instance.kioskoperatorprofile.save()
    if instance.user_type == User.UserType.SUPER_AGENT:
        instance.superagentprofile.save()


@receiver(pre_save, sender=KioskOperatorProfile)
def fetch_coordinates(sender, instance, **kwargs):
    if instance.kiosk_location:
        geolocator = GoogleV3(api_key=settings.GOOGLE_MAPS_API_KEY)
        try:
            location = geolocator.geocode(instance.kiosk_location)
            if location:
                instance.latitude = location.latitude
                instance.longitude = location.longitude
        except GeocoderTimedOut:
            pass

agent_finder/models.py
from django.db import models

# Create your models here.

agent_finder/views.py
from django.shortcuts import render
from .utils import geocode_address, calculate_distance
from accounts.models import KioskOperatorProfile, SuperAgentProfile


def home(request):
    """Home page with search field"""
    context = {}
    search_location = ""
    user_type = "all"  # Default to showing all types

    if request.method == 'POST':
        search_location = request.POST.get('search_location', '')
        user_type = request.POST.get('user_type', 'all')

    if search_location:
        search_location_geo = geocode_address(search_location)
        if search_location_geo:
            # kiosk_operators = []
            results = []

            # Get profiles based on the user_type filter
            # providers_query = KioskOperatorProfile.objects.filter(
            #     is_available=True)
            if user_type == "KO" or user_type == "BS":
                kiosk_operators = KioskOperatorProfile.objects.filter(
                    is_available=True
                ).exclude(
                    latitude__isnull=True
                ).exclude(
                    longitude__isnull=True
                )

                for operator in kiosk_operators:
                    if operator.latitude and operator.longitude:
                        distance = calculate_distance(
                            search_location_geo[0],
                            search_location_geo[1],
                            operator.latitude,
                            operator.longitude
                        )
                        results.append({
                            'operator': operator,
                            'distance': distance,
                            'type': 'KO'
                        })

            if user_type == "SA":
                # super_agents = SuperAgentProfile.objects.exclude(
                #     latitude__isnull=True
                # ).exclude(
                #     longitude__isnull=True
                # )
                super_agents = SuperAgentProfile.objects.all()

                for agent in super_agents:
                    # if agent.latitude and agent.longitude:
                    #     distance = calculate_distance(
                    #         search_location_geo[0],
                    #         search_location_geo[1],
                    #         agent.latitude,
                    #         agent.longitude
                    #     )
                    #     results.append({
                    #         'operator': agent,
                    #         'distance': distance,
                    #         'type': 'SA'
                    #     })
                    results.append({
                        'operator': agent,
                        'distance': 'N/A',
                        'type': 'SA '
                    })

            # Sort by distance
            # kiosk_operators.sort(key=lambda x: x['distance'])
            results.sort(key=lambda x: x['distance'])

            # Limit to 10 closest providers
            # optionally take in a variable to show n closest operators
            # closest_operators = kiosk_operators[:5]
            closest_operators = results[:10]

            context['search_provided'] = True
            context['search_location'] = search_location
            context['closest_operators'] = closest_operators
            context['user_type'] = user_type
        else:
            context['geocoding_error'] = True
            context['user_type'] = user_type

    return render(request, 'agent_finder/home.html', context)

agent_finder/templates/agent_finder/home.html
  {% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row mb-5">
        <div class="col-md-8 offset-md-2 text-center">
            <h1 class="display-4">Find Kiosk Operators, ALS Bets Shops, and Super Agents Near You</h1>
            <p class="lead">Looking for Afro Lottery Systems Kiosks or Super Agents in your area? We'll help you find the closest ones.</p>
        </div>
    </div>

    <div class="row justify-content-center mb-5">
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-body p-4">
                    <form method="post" id="location-search-form">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-md-5">
                                <label for="location" class="form-label">Your Location</label>
                                 <div class="input-group">
                                    <input type="text" id="location" name="search_location" class="form-control" placeholder="Enter your address, city, or zip code" required value="{{ search_location }}">
                                    <button type="button" class="btn btn-secondary" id="detect-location" title="Detect my location">
                                        <i class="bi bi-geo-alt-fill"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <label for="user_type" class="form-label">Looking For</label>
                                <select id="user_type" name="user_type" class="form-select">
                                    {% comment %} <option value="all" {% if user_type == 'all' %}selected{% endif %}>All</option> {% endcomment %}
                                    <option value="KO" {% if user_type == 'KO' %}selected{% endif %}>Kiosk Operators</option>
                                    <option value="SA" {% if user_type == 'SA' %}selected{% endif %}>Super Agents</option>
                                    <option value="BS" {% if user_type == 'BS' %}selected{% endif %}>ALSBets Shops</option>
                                </select>
                            </div>
                            <div class="col-md-2 d-flex align-items-end">
                                <button type="submit" class="btn btn-primary w-100">Search</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            {% if geocoding_error %}
            <div class="alert alert-danger mt-3">
                <i class="bi bi-exclamation-triangle-fill"></i> We couldn't find that location. Please try entering a different address or zip code.
            </div>
            {% endif %}
        </div>
    </div>

    {% if search_provided %}
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <h2>
                {% comment %} Kiosk Operators Near "{{ search_location }}" {% endcomment %}
                {% if user_type == 'KO' %}
                    Kiosk Operators
                {% elif user_type == 'SA' %}
                    Super Agents
                {% elif user_type == 'BS' %}
                    ALSBets Shops
                {% else %}
                    Kiosk Operators, ALSBets Shops, and Super Agents
                {% endif %}
                Near "{{ search_location }}"
            </h2>

            {% if closest_operators %}
                <div class="row mt-4">
                    {% for item in closest_operators %}
                    <div class="col-md-6 mb-4">
                        <div class="card shadow h-100">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.operator.get_full_name }}</h5>
                                <p class="text-muted">
                                    <span class="badge bg-primary">
                                        {{ item.operator.user.get_user_type_display }}
                                    </span>
                                </p>
                                <p>{{ item.operator.kiosk_location }}</p>
                                <p> {{ item.operator.get_state_display }} State</p>
                                <p> {{ item.operator.operating_hours }}</p>
                                <p></i> {{ item.operator.phone_number }}</p>
                                <p><strong>Distance:</strong> {{ item.distance|floatformat:1 }} km away</p>

                                {% comment %} Button for getting directions {% endcomment %}
                                 <button
                                    class="btn btn-outline-primary mt-2 get-directions"
                                    data-dest-lat="{{ item.operator.latitude }}"
                                    data-dest-lng="{{ item.operator.longitude }}"
                                >
                                    Get Directions
                                </button>
                            </div>
                            {% comment %} <div class="card-footer bg-white">
                                <a href="#" class="btn btn-primary">Contact Kiosk Operator</a>
                                <a href="#" class="btn btn-outline-primary">View Profile</a>
                            </div> {% endcomment %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="alert alert-info mt-3">
                    <i class="bi bi-info-circle-fill"></i> No kiosk operators found in your area. Try expanding your search criteria.
                </div>
            {% endif %}
        </div>
    </div>
    {% endif %}
</div>

<script>
document.addEventListener("DOMContentLoaded", function () {
    const locationInput = document.getElementById("location");
    const detectBtn = document.getElementById("detect-location");
    const form = document.getElementById("location-search-form");

    let userLat = null;
    let userLng = null;

    function enableDirectionButtons() {
        document.querySelectorAll('.get-directions').forEach(button => {
            button.addEventListener('click', () => {
                if (userLat !== null && userLng !== null) {
                    const destLat = button.getAttribute('data-dest-lat');
                    const destLng = button.getAttribute('data-dest-lng');
                    const url = `https://www.google.com/maps/dir/?api=1&origin=${userLat},${userLng}&destination=${destLat},${destLng}`;
                    window.open(url, '_blank');
                } else {
                    alert("User location not available yet.");
                }
            });
        });
    }

    function geocodeAddress(address, onSuccess) {
        const url = `https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(address)}`;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                if (data && data.length > 0) {
                    userLat = parseFloat(data[0].lat);
                    userLng = parseFloat(data[0].lon);
                    if (typeof onSuccess === 'function') {
                        onSuccess();
                    }
                } else {
                    alert("Could not find location.");
                }
            })
            .catch(err => {
                console.error(err);
                alert("Failed to geocode address.");
            });
    }

    function setLocationFromGeolocation(onSuccess) {
        if (!navigator.geolocation) {
            alert("Geolocation is not supported by your browser.");
            return;
        }

        detectBtn.disabled = true;
        detectBtn.innerHTML = '<i class="bi bi-geo-alt-fill"></i> Detecting...';

        navigator.geolocation.getCurrentPosition(
            async (position) => {
                userLat = position.coords.latitude;
                userLng = position.coords.longitude;

                try {
                    const response = await fetch(`https://nominatim.openstreetmap.org/reverse?lat=${userLat}&lon=${userLng}&format=json`);
                    const data = await response.json();
                    if (data && data.display_name) {
                        locationInput.value = data.display_name;
                    }
                } catch (error) {
                    console.error(error);
                } finally {
                    detectBtn.disabled = false;
                    detectBtn.innerHTML = '<i class="bi bi-geo-alt"></i>';
                    if (typeof onSuccess === "function") {
                        onSuccess();
                    }
                }
            },
            () => {
                alert("Unable to retrieve your location.");
                detectBtn.disabled = false;
                detectBtn.innerHTML = '<i class="bi bi-geo-alt"></i>';
            }
        );
    }

    // On page load
    if (!locationInput.value) {
        setLocationFromGeolocation(enableDirectionButtons);
    } else {
        // If location was entered manually previously, geocode it
        geocodeAddress(locationInput.value, enableDirectionButtons);
    }

    detectBtn.addEventListener("click", function (e) {
        e.preventDefault();
        setLocationFromGeolocation(enableDirectionButtons);
    });

    // 🧠 Geocode the manually entered location before form submission
    form.addEventListener("submit", function (e) {
        e.preventDefault();  // Stop form for now

        const typedLocation = locationInput.value;
        geocodeAddress(typedLocation, function () {
            form.submit();  // Now submit with updated coordinates
        });
    });
});
</script>

{% endblock %}